services:

  backend:
    build: /backend
    ports: 
      - "3000:3000"
    environment:
      - PG_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

    
  frontend:
    build: /frontend
    ports:
      - "5173:5173"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=market
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5